config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'what_it_is', to: 'pages#what_it_is'
  get 'research', to: 'pages#research'
   get 'contact', to: 'pages#contact'

  # resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "inanna.craigmorse@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contacts_params)
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil# flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
      redirect_to root_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  def contacts_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def what_it_is
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<br>
<br>

<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3 mt-5 p-5 justify-content">

      <h3>We would love to hear from you!</h3>
      <br>

        <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
          <%= f.input :name, :required => true, label: "Your full name" %>
          <%= f.input :email, :required => true %>
          <%= f.input :message, :as => :text, :required => true %>

          <div>
            </br>
            <%= f.button :submit, 'Send message', :class=> "btn" %>
          </div>
      <% end %>

  </div>
</div>

app/views/layouts/_custom_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px;">AWARENESS VR</span>
    <% end %>

<div class="d-flex flex-end">
        <div class="nav-item">
          <%= link_to "about", about_path, class: "nav-link" %>
        </div>

          <div class="nav-item">
          <%= link_to "contact", about_path, class: "nav-link" %>
        </div>

          <div class="nav-item">
          <%= link_to "research", about_path, class: "nav-link" %>
        </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Awareness VR</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="background-color: white;">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<br>

<div class="container justify-content-center align-items-center mt-3">
  <div class="d-flex flex-column justify-content-center align-items-center p-5 mt-5">
    <br>

    <h1>About Awareness VR</h1>
    <p class="p-2">Thanks for visiting! Awareness VR is a project dedicated to bringing easy-to-learn vr meditation exercises to low-income youth in the UK. 34% of children in the UK live under the poverty line, leading to significant, lifelong challenges related to mental health. Meditation practice is proven to ameliorate mental health issues among youth, though it continues to be a challenge for youth to learn it and apply the practice to their lives. Awareness VR aims to make this easier by offering immersive meditation trainings tailored to their needs. </p>


<iframe class="video" height="480" width="700"
src="https://www.youtube.com/embed/kgBBJQDvbU4">
</iframe>
<br>
<br>
<h1>About Me</h1>

    <p>Having meditated for many years, I came to London in 2018 to study at the London School of Economics, where I focused on how innovation can spark new ways of expanding the benefits of meditation. This project is the culmination my dissertation and informed by numerous interviews with vr labs and meditation experts.</p>

   <%= image_tag "profile.jpg", height: 350, width: 350, alt: "alttext" %>
   <br>

      <p>Previously I worked at Human Rights Watch and as a Fulbright scholar to India. </p>

  </div>

</div>

app/views/pages/contact.html.erb
  <br>
  <br>

  <div class="row">
  <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3 mt-5 p-5 justify-content">

   <h3>We would love to hear from you!</h3>
   <br>

  <form  method="POST" action="https://simple-form.com/inanna.craigmorse@gmail.com">
        <input type="hidden" name="redirectURL" value="http://awarenessvr.org" />
        <input class="form-control" type="text" name="name" placeholder="Your name" />
        <br>

        <input class="form-control" type="email" name="replyTo" placeholder="Your email" />
        <br>

        <textarea class="form-control" name="message" placeholder="Your message"></textarea>
        <br>

        <input type="submit" value="Send" class="btn"/>

        </form>

 </div>
</div>

app/views/pages/home.html.erb
<div class="home d-flex justify-content-center align-items-center mt-3";>

  <div class="home-1 d-flex p-5 justify-content-center align-items-center">

      <div class="test d-flex flex-column p-5 justify-between align-items-center">

        <div class="p-1"><h1>AWARENESS VR</h1></div>
        <div class="p-1"><h2>VR meditation exercises tailored to low-income youth</h2></div>
        <div class="p-1"><%= image_tag "logo.png", height: 220, width: 200, crop: :fit, alt: "alttext", class: "logo" %></div>

      </div>
  </div>

</div>

app/views/pages/research.html.erb
<br>

<div class="container justify-content-center align-items-center mt-3">
  <div class="d-flex flex-column justify-content-center align-items-center p-5 mt-5">
    <br>

    <h1>Mental health</h1>
    <p class="p-2">Mental health in the UK is a widespread challenge that disproportionally affects impoverished youth. </p>


<%= image_tag "data.png", height: 250, width: 650, alt: "alttext" %>

<br>
<br>
<h1>Meditation</h1>
    <p>Meditation is a recommended tool to manage mental health (4), and has been successfully integrated into 370 UK schools (5).</p>

   <%= image_tag "circles.png", height: 250, width: 750, alt: "alttext" %>
   <br>

      <p>However, children aged 5-15 continue to find meditation challenging to learn and difficult to apply to their daily lives. </p>

      <%= image_tag "icons.png", height: 280, width: 600, alt: "alttext" %>
      <br>
      <br>

  <h1>Virtual Reality</h1>

    <p>Virtual reality meditation exercises can help overcome these barriers. </p>

       <%= image_tag "circles2.png", height: 220, width: 730, alt: "alttext" %>
   <br>
<br>

<h1>Vision</h1>
<p>Our mission is to significantly reduce rates of mental health issues among low-income youth in the UK by using easy-to-learn vr meditation exercises to help give them the lifelong resource of meditation. We hope that this will inspire related iniatives elsewhere.  </p>
      <%= image_tag "woman1.jpg", height: 400, width: 550, alt: "alttext" %>
      <br>
      <br>

<h1>References</h1>
<ol>
  <li style="font-size: 13px;">Social Metrics Commission 2019 Report:https://socialmetricscommission.org.uk/social-metrics-commission-results-tables-2/</li>
<li style="font-size: 13px;" >Saving Lives: Our healthier nation, Department of Health, 1999 https://www.gov.uk/Government/uploads/ system/uploads/attachment_data/file/265576/4386.pdf</li>
<li style="font-size: 13px;">Mental Health: Poverty, ethnicity and family breakdown, Centre for Social Justice, 2011 http://www. centreforsocialjustice.org.uk/UserStorage/pdf/Pdf%20reports/MentalHealthInterimReport.pdf</li>
<li style="font-size: 13px;">Mental Health Organization, NHS, Harvard Medical School, Center for Anxiety and Traumatic Stress Disorders, Cambridge Health Alliance, University of Massachusetts Medical Center</li>
<li style="font-size: 13px;">Nytimes.com. (2019). Schools in England Introduce a New Subject: Mindfulness. [online] Available at: https://www.nytimes.com/2019/02/04/world/europe/uk-mindfulness-children-school.html [Accessed 24 Nov. 2019].</li>
<li style="font-size: 13px;">Lutz, A., Slagter, H. A., Dunne, J. D., & Davidson, R. J. (2008). Attention regulation and monitoring in meditation. Trends in Cognitive Sciences, 12(4), 163–169.</li>
<li style="font-size: 13px;">Metz, S. M., Frank, J. L., Reibel, D., Cantrell, T., Sanders, R., & Broderick, P. C. (2013). The effectiveness of the learning to BREATHE program on adolescent emotion regulation. Research in Human Development, 10(3), 252–272.</li>
<li style="font-size: 13px;">Liehr, P., & Diaz, N. (2010). A Pilot Study Examining the Effect of Mindfulness on Depression and Anxiety for Minority Children. Archives of Psychiatric Nursing, 24(1), 69–71.</li>
<li style="font-size: 13px;">Jones, A. (2013, June 10). Meditation in schools: calming minds and beating stress. Retrieved from https://www.theguardian.com/teacher-network/teacher-blog/2013/jun/10/meditation-mindfulness-schools-stress-calming-classrooms.</li>
<li style="font-size: 13px;">Navarro-Haro MV, López-del-Hoyo Y, Campos D, Linehan MM, Hoffman HG, García-Palacios A, et al. (2017) Meditation experts try Virtual Reality Mindfulness: A pilot study evaluation of the feasibility and acceptability of Virtual Reality to facilitate mindfulness practice in people attending a Mindfulness conference. PLoS ONE 12(11): e0187777.https://doi.org/10.1371/journal.pone.0187777</li>
<li style="font-size: 13px;">Isacsson, D. (2016, February 1). Report: Youths Want Virtual Reality. Retrieved from https://www.digitaltrends.com/virtual-reality/report-youths-want-vr/.</li>

</ol>



  </div>

</div>

app/views/pages/what_it_is.html.erb
<br>

<div class="main d-flex justify-content-space-between p-5 ">

  <div class="main justify-content-center align-items-center mt-3">
    <div class="d-flex flex-column justify-content-center align-items-center p-5 mt-5">
      <br>

      <h1>Product</h1>
      <p class="p-2">A series of guided vr meditation exercises tailored to youth designed by meditation and education experts.</p>
      <br>
      <p>1. VR exercises can make meditation easier to learn by capturing participants’ attention and gives users the illusion of “being there”. </p>

     <%= image_tag "undraw_augmented_reality.png", height: 300, width: 350, alt: "alttext"%>
      <br>
      <p>2. And it can simulate home dynamics or social situations, allowing users to practice applying meditation to real-life situations </p>

     <%= image_tag "undraw_a_day_at_the_park.png", height: 300, width: 370, alt: "alttext" %>

    </div>

  </div>

   <div class="main justify-content-center align-items-center mt-3">
    <div class="d-flex flex-column justify-content-center align-items-center p-5 mt-5">
      <br>

      <h1>Trainings</h1>
      <p class="p-2">In person guided meditations using the exercises in schools in low income areas.</p>
      <br>
      <p>1. Trainings provide headsets to all students. </p>

     <%= image_tag "undraw_virtual_reality.png", height: 300, width: 400, alt: "alttext" %>
      <br>
      <p>2. And involve post-training discussion. </p>

     <%= image_tag "undraw_hang_out.png", height: 300, width: 370, alt: "alttext" %>
     <br>
      <p>3. And tips for ways to practice meditation outside of the headset. </p>

     <%= image_tag "undraw_mindfulness.png", height: 300, width: 370, alt: "alttext" %>

    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px;">AWARENESS VR</span>
    <% end %>

<div class="d-flex flex-end">
        <div class="nav-item">
          <%= link_to "about", about_path, class: "nav-link" %>
        </div>

          <div class="nav-item">
          <%= link_to "what it is", what_it_is_path, class: "nav-link" %>
        </div>

          <div class="nav-item">
          <%= link_to "research", research_path, class: "nav-link" %>
        </div>

        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link" %>
        </div>
</div>

</div>